import Head from "next/head";
import { useState } from "react";
import Character from "components/Character";
import classes from "styles/Home.module.css";

export default function Characters({ characters }) {
  const [value, setValue] = useState(12);

  const handleShowMore = () => {
    setValue(value + 12);
  };

  return (
    <div className="bg-starwars-color">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col h-screen mx-auto justify-center w-[calc(100%-400px)]">
        <div className="bg-starwars-color w-full flex mt-200 p-30 justify-center gap-25 flex-wrap">
          {characters
            .filter((character) => character.id !== 28 && character.id !== 77)
            .map(
              (character, index) =>
                index < value && (
                  <Character
                    character={character}
                    key={character.id}
                  ></Character>
                )
            )}
        </div>
        {value < characters.length && (
          <button
            className="group relative mt-4 box-border ease-linear duration-100 text-white/[.4] font-bold py-2 rounded-sm mx-auto block hover:text-white"
            onClick={handleShowMore}
          >
            <span className="ease-linear duration-100 w-[40%] h-[2px] block absolute left-[50%] bottom-0 translate-x-[-50%] bg-transparent group-hover:w-full group-hover:bg-white"></span>
            SHOW MORE
          </button>
        )}
      </div>
      <div className="w-[232px] h-screen fixed left-0 top-0 blockbg-repeat-y bg-[url('https://static-mh.content.disney.io/starwars/assets/background/bg_starsL-fd4661a3ccea.jpg')]"></div>
      <div className="w-[232px] h-screen fixed right-0 top-0 blockbg-repeat-y bg-[url('https://static-mh.content.disney.io/starwars/assets/background/bg_starsR-655c85e404d4.jpg')]"></div>
    </div>
  );
}
export async function getStaticProps(context) {
  const characters = await fetch(
    "https://akabab.github.io/starwars-api/api/all.json"
  ).then((res) => res.json());
  return {
    props: {
      characters,
    },
  };
}
